# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/Config.ipynb.

# %% auto 0
__all__ = ['Config']

# %% ../nbs/Config.ipynb 2
class Config:
    "Class to define config for the project"
    base_dataset_path  = '../datasets/cola_public/raw/'
    base_model_name = 'microsoft/deberta-v3-large'


