# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/Config.ipynb.

# %% auto 0
__all__ = ['Config']

# %% ../nbs/Config.ipynb 2
class Config:
    "Class to define config for the project"
    base_dataset_path = "../data/cola_public/raw/"
    base_model_name = "microsoft/deberta-v3-large"

    train_path = f"{base_dataset_path}in_domain_train.tsv"

    # Model Params
    context_length = 512  # Maximum sentence length
    num_classes = 2

    # Training Params
    train_batch_size = 8
    val_batch_size = 8
    test_batch_size = 1
